import test from "node:test";
import assert from "node:assert/strict";
import { chmodSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { createPublisherServer } from "../src/web-server.ts";
import { openDatabase } from "../src/database.ts";
import { PublisherStore } from "../src/publisher-store.ts";

test("local dashboard exposes read-only SQLite jobs and no-AI health contract", async () => {
  const root = mkdtempSync(join(tmpdir(), "publisher-web-"));
  const dbPath = join(root, "publisher.sqlite");
  const contentRoot = join(root, "content"); mkdirSync(contentRoot);
  writeFileSync(join(contentRoot, "Daily-018-cover.png"), Buffer.from([137,80,78,71,13,10,26,10,1]));
  writeFileSync(join(contentRoot, "Daily-018-xiaohongshu-public.txt"), "测试标题\n测试正文");
  writeFileSync(join(contentRoot, "Daily-018-facebook-public.txt"), "测试标题\n测试正文");
  writeFileSync(join(root, "ledger.yaml"), "published_history: {}\n");
  const db = openDatabase(dbPath);
  const store = new PublisherStore(db);
  const jobId = store.createJob({ articleId: "Daily-017", platform: "wechat_channels", accountId: "sph42vLa6y4BW9x", packageHash: "a".repeat(64), approvalRef: "approval-1" });
  store.transition(jobId, "FACT_CHECK", { source: "test" });
  db.close();
  const server = createPublisherServer({ dbPath, contentRoots: [contentRoot], ledgerPath: join(root, "ledger.yaml"), stagingRoot: join(root, "staging"), mirrorPath: join(root, "events.jsonl"), workerEnabled: false });
  await new Promise<void>(resolve => server.listen(0, "127.0.0.1", resolve));
  const address = server.address();
  assert.ok(address && typeof address === "object");
  const base = `http://127.0.0.1:${address.port}`;
  try {
    const health = await (await fetch(`${base}/api/health`)).json() as any;
    assert.equal(health.aiRuntimeRequired, false);
    assert.equal(health.capabilities.wechat_channels.validation, "historically_verified_browser_flow");
    const jobs = await (await fetch(`${base}/api/jobs`)).json() as any;
    assert.equal(jobs.jobs[0].article_id, "Daily-017");
    const detail = await (await fetch(`${base}/api/jobs/${jobId}`)).json() as any;
    assert.equal(detail.history[0].to_state, "FACT_CHECK");
    const page = await (await fetch(base)).text();
    assert.match(page, /VietBridge 多平台发布器/);
    assert.match(page, /日常流程不调用 AI/);
    assert.match(page, /筛选可发布内容/);
    assert.doesNotMatch(page, /保存任务草稿/);
    assert.doesNotThrow(()=>new Function(page.match(/<script>([\s\S]*?)<\/script>/)![1]));
    assert.match(page,/Facebook 发布账号/);
    const accountFile=join(root,'second.env');writeFileSync(accountFile,'FB_ACCOUNT_NAME=Second\nFB_PAGE_ID=2002\nFB_PAGE_NAME=Second Page\nFB_PAGE_ACCESS_TOKEN=never-return-this\n');chmodSync(accountFile,0o600);
    const imported=await (await fetch(`${base}/api/facebook/accounts/import`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({config_url:`file://${accountFile}`})})).json() as any;
    assert.equal(imported.page_id,'2002');assert.doesNotMatch(JSON.stringify(imported),/never-return-this/);
    const saved=await (await fetch(`${base}/api/facebook/accounts`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(imported)})).json() as any;
    assert.equal((await fetch(`${base}/api/facebook/accounts/select`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:saved.id})})).status,200);
    const accountList=await (await fetch(`${base}/api/facebook/accounts`)).json() as any;assert.equal(accountList.selectedAccountId,saved.id);
    assert.match(page,/data-wechat-reconcile/);
    const facebookCandidates=await (await fetch(`${base}/api/content/candidates?platforms=facebook`)).json() as any;
    assert.equal(facebookCandidates.candidates.length,1);
    assert.equal(facebookCandidates.candidates[0].articleId,'Daily-018');
    const previewAsset=facebookCandidates.candidates[0].assets[0];
    const previewUrl=new URL('/api/content/asset',base);previewUrl.searchParams.set('path',previewAsset.path);previewUrl.searchParams.set('revision',previewAsset.revision);
    const previewResponse=await fetch(previewUrl);assert.equal(previewResponse.status,200);assert.equal(previewResponse.headers.get('x-asset-revision'),previewAsset.revision);
    assert.match(previewResponse.headers.get('cache-control')??'',/immutable/);
    const staleUrl=new URL(previewUrl);staleUrl.searchParams.set('revision','0'.repeat(64));assert.equal((await fetch(staleUrl)).status,409);
    const channelsCandidates=await (await fetch(`${base}/api/content/candidates?platforms=wechat_channels`)).json() as any;
    assert.equal(channelsCandidates.candidates.length,0);
    assert.equal((await fetch(`${base}/api/jobs/${jobId}/wechat-reconcile`,{method:'POST'})).status,409);
    writeFileSync(join(contentRoot,"Daily-018-wechat-companion-public.md"),"# 公众号测试标题\n公开正文");
    const wechat = await fetch(`${base}/api/tasks/execute`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({mode:"article_id",value:"Daily-018",platforms:["wechat_official_account"]})});
    assert.equal(wechat.status,201);
    const wechatBatch = await wechat.json() as any;
    assert.equal(wechatBatch.jobs[0].platform,"wechat_official_account");
    assert.equal(wechatBatch.control_state,"AWAITING_APPROVAL");
    const manualDeleteDb=openDatabase(dbPath);
    manualDeleteDb.prepare("UPDATE jobs SET state='DRAFT_API_WRITTEN_NOT_PUBLISHED' WHERE job_id=?").run(wechatBatch.jobs[0].job_id);
    manualDeleteDb.close();
    const existingDraft=await fetch(`${base}/api/tasks/execute`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode:'article_id',value:'Daily-018',platforms:['wechat_official_account']})});
    assert.equal(existingDraft.status,409);
    assert.match(JSON.stringify(await existingDraft.json()),/已有发布记录或公众号草稿/);
    const draftCandidate=await (await fetch(`${base}/api/content/candidates?platforms=xiaohongshu&includeIncomplete=1`)).json() as any;
    assert.deepEqual(draftCandidate.candidates.find((x:any)=>x.articleId==='Daily-018').draftPlatforms,['wechat_official_account']);
    const manualDeleted=await fetch(`${base}/api/jobs/${wechatBatch.jobs[0].job_id}/wechat-manual-deleted`,{method:'POST'});
    assert.equal(manualDeleted.status,200);
    const manualDeletedBatch=await manualDeleted.json() as any;
    assert.equal(manualDeletedBatch.jobs[0].state,'PLATFORM_DELETED');
    const created = await fetch(`${base}/api/tasks/execute`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ mode: "article_id", value: "Daily-018", platforms: ["xiaohongshu", "facebook"] }) });
    assert.equal(created.status, 201);
    const batch = await created.json() as any;
    assert.equal(batch.jobs.length, 2);
    assert.equal(batch.control_state, "AWAITING_APPROVAL");
    const failureDb=openDatabase(dbPath);
    failureDb.prepare("UPDATE jobs SET state='FAILED_PREFLIGHT' WHERE batch_id=?").run(batch.batch_id);
    failureDb.prepare("UPDATE publication_batches SET control_state='COMPLETED' WHERE batch_id=?").run(batch.batch_id);
    const beforeCount=(failureDb.prepare('SELECT COUNT(*) AS n FROM publication_batches').get() as any).n;
    const recreated=await (await fetch(`${base}/api/tasks/execute`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode:'article_id',value:'Daily-018',platforms:['xiaohongshu','facebook']})})).json() as any;
    assert.equal(recreated.batch_id,batch.batch_id);
    assert.equal(recreated.control_state,'AWAITING_APPROVAL');
    assert.ok(recreated.jobs.every((j:any)=>j.state==='READY_FOR_USER_APPROVAL'));
    assert.equal((failureDb.prepare('SELECT COUNT(*) AS n FROM publication_batches').get() as any).n,beforeCount);
    failureDb.close();
    assert.equal((await fetch(`${base}/api/batches/${batch.batch_id}/approve`, { method: "POST" })).status, 200);
    const editDb = openDatabase(dbPath);
    const retryId = batch.jobs.find((j:any)=>j.platform === 'xiaohongshu').job_id;
    new PublisherStore(editDb).transition(retryId, 'FAILED_PREFLIGHT', {error:'Xiaohongshu MCP did not start'});
    editDb.prepare("UPDATE publication_batches SET control_state='COMPLETED' WHERE batch_id=?").run(batch.batch_id);
    const shown = await (await fetch(`${base}/api/batches`)).json() as any;
    const failed = shown.batches[0].jobs.find((j:any)=>j.job_id===retryId);
    assert.match(failed.failure_reason, /小红书本地服务/);
    assert.equal(failed.can_retry, true);
    assert.equal(failed.can_resume_stopped,true);
    assert.equal((await fetch(`${base}/api/jobs/${retryId}/retry`,{method:'POST'})).status,200);
    assert.equal((await fetch(`${base}/api/jobs/${retryId}/retry`,{method:'POST'})).status,409);
    new PublisherStore(editDb).transition(retryId,'FAILED_PREFLIGHT',{error:'timeout'});
    editDb.prepare("UPDATE jobs SET submit_safety_domain='MAY_HAVE_SUBMITTED' WHERE job_id=?").run(retryId);
    editDb.prepare("UPDATE publication_batches SET control_state='COMPLETED' WHERE batch_id=?").run(batch.batch_id);
    assert.equal((await fetch(`${base}/api/jobs/${retryId}/retry`,{method:'POST'})).status,409);
    editDb.close();
    assert.equal((await fetch(`${base}/api/batches/${batch.batch_id}/stop`,{method:'POST'})).status,200);
    const stopped = await (await fetch(`${base}/api/batches`)).json() as any;
    assert.equal(stopped.batches[0].control_state,'TERMINATED');
    const resumed=await fetch(`${base}/api/batches/${batch.batch_id}/resume`,{method:'POST'});
    assert.equal(resumed.status,200);
    const resumedBatch=await resumed.json() as any;
    assert.equal(resumedBatch.control_state,'AWAITING_APPROVAL');
    assert.equal(resumedBatch.pause_requested,0);
    assert.equal(resumedBatch.jobs.find((j:any)=>j.platform==='facebook').state,'READY_FOR_USER_APPROVAL');
    assert.equal(resumedBatch.jobs.find((j:any)=>j.job_id===retryId).state,'FAILED_PREFLIGHT');
    const duplicateDb=openDatabase(dbPath);
    const fbJob=batch.jobs.find((j:any)=>j.platform==='facebook');
    new PublisherStore(duplicateDb).transition(fbJob.job_id,'FAILED_PREFLIGHT',{reason:'DUPLICATE_OR_UNRESOLVED_JOB',existing:{state:'PUBLISHED'}});
    duplicateDb.prepare("UPDATE publication_batches SET control_state='TERMINATED' WHERE batch_id=?").run(batch.batch_id);
    const duplicateBatches=await (await fetch(`${base}/api/batches`)).json() as any;
    const duplicateBatch=duplicateBatches.batches.find((entry:any)=>entry.batch_id===batch.batch_id);
    const duplicateJob=duplicateBatch.jobs.find((j:any)=>j.job_id===fbJob.job_id);
    assert.match(duplicateJob.failure_reason,/Facebook 已有发布记录/);
    assert.equal(duplicateJob.can_resume_stopped,false);
    duplicateDb.prepare("UPDATE publication_batches SET control_state='AWAITING_APPROVAL' WHERE batch_id=?").run(batch.batch_id);
    duplicateDb.close();
    await fetch(`${base}/api/batches/${batch.batch_id}/stop`,{method:'POST'});
    assert.equal((await fetch(`${base}/api/history/clear`,{method:'POST'})).status,200);
    const hidden=await (await fetch(`${base}/api/batches`)).json() as any;
    assert.ok(hidden.batches[0].jobs.every((j:any)=>j.history_hidden));
    assert.equal((await fetch(`${base}/api/history/restore`,{method:'POST'})).status,200);
    const restored=await (await fetch(`${base}/api/batches`)).json() as any;
    assert.ok(restored.batches[0].jobs.every((j:any)=>!j.history_hidden));
    const completeDb=openDatabase(dbPath);
    completeDb.prepare("UPDATE jobs SET state='PUBLISHED' WHERE article_id='Daily-018'").run();
    completeDb.close();
    const exhausted=await (await fetch(`${base}/api/content/resolve`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode:'ledger',platforms:['facebook']})})).json() as any;
    assert.equal(exhausted.status,'NEEDS_SUPPLEMENT');
    const defaultCandidates=await (await fetch(`${base}/api/content/candidates?platforms=facebook`)).json() as any;
    assert.ok(!defaultCandidates.candidates.some((item:any)=>item.articleId==='Daily-018'));
    const republishCandidates=await (await fetch(`${base}/api/content/candidates?platforms=facebook&includePublished=1`)).json() as any;
    assert.ok(republishCandidates.candidates.some((item:any)=>item.articleId==='Daily-018'));
    const republished=await fetch(`${base}/api/tasks/execute`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode:'article_id',value:'Daily-018',platforms:['facebook'],republish:true})});
    assert.equal(republished.status,201);
    const republishedBatch=await republished.json() as any;
    assert.match(republishedBatch.title,/^重新发布 · /);
    assert.equal(republishedBatch.jobs.length,1);
    assert.equal(republishedBatch.jobs[0].platform,'facebook');
    assert.notEqual(republishedBatch.jobs[0].job_id,batch.jobs.find((job:any)=>job.platform==='facebook').job_id);
    writeFileSync(join(contentRoot,'Daily-017-cover.png'),Buffer.from([137,80,78,71,13,10,26,10,1]));
  writeFileSync(join(contentRoot,'Daily-017-facebook-public.txt'),'下一篇标题\n正文');
    const next=await (await fetch(`${base}/api/content/resolve`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode:'ledger',platforms:['facebook']})})).json() as any;
    assert.equal(next.package.articleId,'Daily-017');
    assert.equal((await fetch(`${base}/api/jobs`, { method: "POST" })).status, 405);
  } finally {
    await new Promise<void>((resolveClose, reject) => server.close(error => error ? reject(error) : resolveClose()));
    rmSync(root, { recursive: true, force: true });
  }
});

test('existing WeChat draft does not block creating a separate Xiaohongshu task', async()=>{
  const root=mkdtempSync(join(tmpdir(),'publisher-draft-isolation-'));
  const dbPath=join(root,'publisher.sqlite'),contentRoot=join(root,'content');mkdirSync(contentRoot);
  writeFileSync(join(contentRoot,'Daily-999-cover.png'),Buffer.from([137,80,78,71,13,10,26,10,1]));
  writeFileSync(join(contentRoot,'Daily-999-wechat-companion-public.md'),'# 可发布文章\n正文');
  writeFileSync(join(contentRoot,'Daily-999-xiaohongshu-public.txt'),'测试标题\n测试正文');
  const server=createPublisherServer({dbPath,contentRoots:[contentRoot],stagingRoot:join(root,'staging'),mirrorPath:join(root,'events.jsonl'),workerEnabled:false});
  await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));
  const address=server.address();assert.ok(address&&typeof address==='object');
  const base=`http://127.0.0.1:${address.port}`;
  try{
    const initial=await fetch(`${base}/api/tasks/execute`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode:'article_id',value:'Daily-999',platforms:['wechat_official_account']})});
    assert.equal(initial.status,201,await initial.clone().text());
    const draftBatch=await initial.json() as any;
    const db=openDatabase(dbPath);
    db.prepare("UPDATE jobs SET state='DRAFT_API_WRITTEN_NOT_PUBLISHED' WHERE job_id=?").run(draftBatch.jobs[0].job_id);
    db.close();
    const mixed=await fetch(`${base}/api/tasks/execute`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode:'article_id',value:'Daily-999',platforms:['xiaohongshu','wechat_official_account']})});
    assert.equal(mixed.status,201);
    const batch=await mixed.json() as any;
    assert.deepEqual(batch.jobs.map((job:any)=>job.platform),['xiaohongshu']);
    assert.equal(batch.control_state,'AWAITING_APPROVAL');
    const explicit=await fetch(`${base}/api/tasks/execute`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode:'article_id',value:'Daily-999',platforms:['wechat_official_account'],republish:true})});
    assert.equal(explicit.status,201,await explicit.clone().text());
    const repeatedDraft=await explicit.json() as any;
    assert.notEqual(repeatedDraft.batch_id,draftBatch.batch_id);
    assert.equal(repeatedDraft.jobs[0].state,'READY_FOR_USER_APPROVAL');
    assert.notEqual(repeatedDraft.jobs[0].job_id,draftBatch.jobs[0].job_id);
    const accidentalDoubleClick=await fetch(`${base}/api/tasks/execute`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode:'article_id',value:'Daily-999',platforms:['wechat_official_account'],republish:true})});
    assert.equal(accidentalDoubleClick.status,400);
    assert.match(JSON.stringify(await accidentalDoubleClick.json()),/已有待确认的重复发布任务/);
    const retryDb=openDatabase(dbPath);
    retryDb.prepare("UPDATE jobs SET state='FAILED_PREFLIGHT',submit_safety_domain='BEFORE_EXTERNAL_SUBMIT',approval_ref='test-approval' WHERE job_id=?").run(repeatedDraft.jobs[0].job_id);
    retryDb.prepare("UPDATE publication_batches SET control_state='TERMINATED' WHERE batch_id=?").run(repeatedDraft.batch_id);
    retryDb.close();
    const authorizedRetry=await fetch(`${base}/api/jobs/${repeatedDraft.jobs[0].job_id}/retry`,{method:'POST'});
    assert.equal(authorizedRetry.status,200,await authorizedRetry.clone().text());
    assert.equal((await authorizedRetry.json() as any).jobs[0].state,'PLATFORM_PREFLIGHT');
    const whitelistDb=openDatabase(dbPath);
    whitelistDb.prepare("UPDATE jobs SET state='FAILED_PREFLIGHT' WHERE job_id=?").run(repeatedDraft.jobs[0].job_id);
    whitelistDb.prepare("INSERT INTO state_transitions(job_id,from_state,to_state,event_id,evidence_json,created_at) VALUES(?,?,?,?,?,?)")
      .run(repeatedDraft.jobs[0].job_id,'PLATFORM_PREFLIGHT','FAILED_PREFLIGHT','wechat-ip-regression',JSON.stringify({error:'微信接口错误码 40164',liveRequestSent:false}),'2099-01-01T00:00:00Z');
    whitelistDb.close();
    const status=await (await fetch(`${base}/api/batches`)).json() as any;
    const failed=status.batches.find((item:any)=>item.batch_id===repeatedDraft.batch_id).jobs[0];
    assert.match(failed.failure_reason,/IP.*白名单|IP.*开发者白名单/);
  }finally{
    await new Promise<void>((resolveClose,reject)=>server.close(error=>error?reject(error):resolveClose()));
    rmSync(root,{recursive:true,force:true});
  }
});
