export const JOB_STATES = [
  "STORED_NOT_SCHEDULED", "FACT_CHECK", "EDITORIAL_REVIEW",
  "READY_FOR_USER_APPROVAL", "USER_APPROVED", "PLATFORM_PREFLIGHT",
  "PUBLICATION_INTENT_COMMITTED", "FORM_FILLING", "FORM_FILLED",
  "SUBMITTED_PENDING_CONFIRMATION", "UNKNOWN", "RECONCILE_PENDING",
  "JOB_WAITING_HUMAN", "SESSION_EXPIRED", "PROFILE_LOCKED",
  "PUBLISHED", "PUBLISHED_ID_PENDING", "DRAFT_API_WRITTEN_NOT_PUBLISHED",
  "PLATFORM_DELETED", "FAILED_PREFLIGHT", "FAILED", "BLOCKED_CAPABILITY"
] as const;

export type JobState = typeof JOB_STATES[number];

export const TERMINAL_STATES = new Set<JobState>([
  "PUBLISHED", "PUBLISHED_ID_PENDING", "DRAFT_API_WRITTEN_NOT_PUBLISHED",
  "PLATFORM_DELETED", "FAILED_PREFLIGHT", "FAILED", "BLOCKED_CAPABILITY"
]);

const normal: Record<string, JobState[]> = {
  PUBLISHED_ID_PENDING: ['PUBLISHED'],
  DRAFT_API_WRITTEN_NOT_PUBLISHED: ['PLATFORM_DELETED'],
  STORED_NOT_SCHEDULED: ["FACT_CHECK"],
  FACT_CHECK: ["EDITORIAL_REVIEW", "FAILED_PREFLIGHT"],
  EDITORIAL_REVIEW: ["READY_FOR_USER_APPROVAL", "FAILED_PREFLIGHT"],
  READY_FOR_USER_APPROVAL: ["USER_APPROVED", "FAILED_PREFLIGHT"],
  USER_APPROVED: ["PLATFORM_PREFLIGHT", "FAILED_PREFLIGHT", "BLOCKED_CAPABILITY"],
  PLATFORM_PREFLIGHT: ["PUBLICATION_INTENT_COMMITTED", "FAILED_PREFLIGHT", "SESSION_EXPIRED", "PROFILE_LOCKED", "JOB_WAITING_HUMAN", "BLOCKED_CAPABILITY"],
  PUBLICATION_INTENT_COMMITTED: ["FORM_FILLING", "SUBMITTED_PENDING_CONFIRMATION", "FAILED_PREFLIGHT", "JOB_WAITING_HUMAN"],
  FORM_FILLING: ["FORM_FILLED", "FAILED_PREFLIGHT", "SESSION_EXPIRED", "JOB_WAITING_HUMAN"],
  FORM_FILLED: ["SUBMITTED_PENDING_CONFIRMATION", "FAILED_PREFLIGHT", "SESSION_EXPIRED", "JOB_WAITING_HUMAN"],
  SUBMITTED_PENDING_CONFIRMATION: ["PUBLISHED", "PUBLISHED_ID_PENDING", "DRAFT_API_WRITTEN_NOT_PUBLISHED", "UNKNOWN", "FAILED"],
  UNKNOWN: ["RECONCILE_PENDING"],
  RECONCILE_PENDING: ["PUBLISHED", "PUBLISHED_ID_PENDING", "DRAFT_API_WRITTEN_NOT_PUBLISHED", "FAILED", "JOB_WAITING_HUMAN"],
  SESSION_EXPIRED: ["JOB_WAITING_HUMAN", "PLATFORM_PREFLIGHT"],
  PROFILE_LOCKED: ["PLATFORM_PREFLIGHT", "FAILED_PREFLIGHT"],
  JOB_WAITING_HUMAN: ["PLATFORM_PREFLIGHT", "FORM_FILLING", "FORM_FILLED", "RECONCILE_PENDING", "FAILED"]
};

export function canTransition(from: JobState, to: JobState): boolean {
  return normal[from]?.includes(to) ?? false;
}
